### POST request to create a new patient
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name": "John Doe with billing account",
  "email": "test12343@example.com",
  "address": "124 main  st. Springfield",
  "dateOfBirth": "1985-06-15",
  "registeredDate": "2025-01-10"
}

### Response
